cannot_change_category = 'Category cannot be changed'
cannot_change_state = 'State cannot be changed'
category_not_found = 'Category does not exist'
criterion_not_found = 'Criterion does not exist'
invalid_state = 'State code is invalid'
link_not_found = 'Link does not exist'
invalid_grade = 'Grades must be one of (-1, 0, 1, 2, or 3)'
