"""empty message

Revision ID: 128cf56cc86e
Revises: 4b4cc49e9ce1
Create Date: 2021-01-26 22:38:25.712714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128cf56cc86e'
down_revision = '4b4cc49e9ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('help_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('states',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('criteria',
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('recommendation_text', sa.String(), nullable=True),
    sa.Column('help_text', sa.String(), nullable=True),
    sa.Column('adverse', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_criteria_category_id'), 'criteria', ['category_id'], unique=False)
    op.create_table('links',
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['state'], ['states.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('honorable_mention_state_category_active', 'links', ['state', 'category_id', 'active'], unique=False)
    op.create_index('innovative_idea_state_category_active', 'links', ['state', 'category_id', 'active'], unique=False)
    op.create_index('state_category', 'links', ['state', 'category_id'], unique=False)
    op.create_table('state_category_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['state_code'], ['states.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['state_code'], ['states.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('meets_criterion', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criterion_id'], ['criteria.id'], ),
    sa.ForeignKeyConstraint(['state'], ['states.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('state_criterion_created_at', 'scores', ['state', 'criterion_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('state_criterion_created_at', table_name='scores')
    op.drop_table('scores')
    op.drop_table('state_grades')
    op.drop_table('state_category_grades')
    op.drop_index('state_category', table_name='links')
    op.drop_index('innovative_idea_state_category_active', table_name='links')
    op.drop_index('honorable_mention_state_category_active', table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_criteria_category_id'), table_name='criteria')
    op.drop_table('criteria')
    op.drop_table('states')
    op.drop_table('categories')
    # ### end Alembic commands ###
