"""empty message

Revision ID: 16600183a58f
Revises: 2bd5e2771980
Create Date: 2020-10-29 15:21:06.795006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16600183a58f'
down_revision = '2bd5e2771980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('state_criterion_created_at', 'scores', ['state', 'criterion_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('state_criterion_created_at', table_name='scores')
    # ### end Alembic commands ###
