"""empty message

Revision ID: 209e7b23d650
Revises: 26353f0d2a3d
Create Date: 2020-12-24 21:34:04.313523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209e7b23d650'
down_revision = '26353f0d2a3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'subcategories',
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('deactivated_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('help_text', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_subcategories_category_id'),
        'subcategories',
        ['category_id'],
        unique=False,
    )
    op.add_column('criteria', sa.Column('subcategory_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_criteria_subcategory_id'), 'criteria', ['subcategory_id'], unique=False)
    op.drop_index('ix_criteria_category_id', table_name='criteria')
    op.drop_constraint('criteria_category_id_fkey', 'criteria', type_='foreignkey')
    op.create_foreign_key(None, 'criteria', 'subcategories', ['subcategory_id'], ['id'])
    op.drop_column('criteria', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criteria', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'criteria', type_='foreignkey')
    op.create_foreign_key('criteria_category_id_fkey', 'criteria', 'categories', ['category_id'], ['id'])
    op.create_index('ix_criteria_category_id', 'criteria', ['category_id'], unique=False)
    op.drop_index(op.f('ix_criteria_subcategory_id'), table_name='criteria')
    op.drop_column('criteria', 'subcategory_id')
    op.drop_index(op.f('ix_subcategories_category_id'), table_name='subcategories')
    op.drop_table('subcategories')
    # ### end Alembic commands ###
