"""empty message

Revision ID: 26353f0d2a3d
Revises: 7f96dfa7fc64
Create Date: 2020-12-06 22:03:34.750117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26353f0d2a3d'
down_revision = '7f96dfa7fc64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('links', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'deactivated_at')
    op.drop_column('links', 'active')
    # ### end Alembic commands ###
