"""empty message

Revision ID: 286ee9b358b4
Revises: b27431512ca4
Create Date: 2021-04-03 13:08:51.956341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286ee9b358b4'
down_revision = 'b27431512ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('states', sa.Column('quote', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('states', 'quote')
    # ### end Alembic commands ###
