"""empty message

Revision ID: 2c87d4e793c0
Revises: d05d8a998a58
Create Date: 2020-12-06 21:15:34.232489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c87d4e793c0'
down_revision = 'd05d8a998a58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_index('state_category', 'links', ['state', 'category_id'], unique=False)
    op.drop_index('state_criterion', table_name='links')
    op.drop_constraint('links_criterion_id_fkey', 'links', type_='foreignkey')
    op.create_foreign_key(None, 'links', 'categories', ['category_id'], ['id'])
    op.drop_column('links', 'criterion_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('criterion_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.create_foreign_key('links_criterion_id_fkey', 'links', 'criteria', ['criterion_id'], ['id'])
    op.create_index('state_criterion', 'links', ['state', 'criterion_id'], unique=False)
    op.drop_index('state_category', table_name='links')
    op.drop_column('links', 'category_id')
    # ### end Alembic commands ###
