"""empty message

Revision ID: 31e162d0f348
Revises: 75e2b2aee94a
Create Date: 2021-02-05 14:04:52.297503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31e162d0f348'
down_revision = '75e2b2aee94a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'description')
    # ### end Alembic commands ###
