"""empty message

Revision ID: 4b4cc49e9ce1
Revises: bb239b87fe29
Create Date: 2021-01-23 14:36:01.338549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b4cc49e9ce1'
down_revision = 'bb239b87fe29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_subcategory_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['state_code'], ['states.code'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('state_category_grades')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_category_grades',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('state_code', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='state_category_grades_category_id_fkey'),
    sa.ForeignKeyConstraint(['state_code'], ['states.code'], name='state_category_grades_state_code_fkey'),
    sa.PrimaryKeyConstraint('id', name='state_category_grades_pkey')
    )
    op.drop_table('state_subcategory_grades')
    # ### end Alembic commands ###
