"""empty message

Revision ID: 52f7f51d21b1
Revises: ea276fcdfa35
Create Date: 2021-01-14 12:35:50.498441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52f7f51d21b1'
down_revision = 'ea276fcdfa35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('type', sa.String(length=20), nullable=True))
    op.drop_index('honorable_mention_state_subcategory_active', table_name='links')
    op.drop_index('innovative_idea_state_subcategory_active', table_name='links')
    op.drop_column('links', 'created_at')
    op.add_column('states', sa.Column('honorable_mention', sa.String(), nullable=True))
    op.add_column('states', sa.Column('innovative_idea', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('states', 'innovative_idea')
    op.drop_column('states', 'honorable_mention')
    op.add_column('links', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('innovative_idea_state_subcategory_active', 'links', ['state', 'subcategory_id', 'active'], unique=False)
    op.create_index('honorable_mention_state_subcategory_active', 'links', ['state', 'subcategory_id', 'active'], unique=False)
    op.drop_column('links', 'type')
    # ### end Alembic commands ###
