"""empty message

Revision ID: 5460b36b985f
Revises: d7c80ade926a
Create Date: 2020-11-02 17:31:36.337830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5460b36b985f'
down_revision = 'd7c80ade926a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('help_text', sa.String(), nullable=True))
    op.add_column('criteria', sa.Column('help_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('criteria', 'help_text')
    op.drop_column('categories', 'help_text')
    # ### end Alembic commands ###
