"""empty message

Revision ID: 7f96dfa7fc64
Revises: 2c87d4e793c0
Create Date: 2020-12-06 21:26:43.181069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f96dfa7fc64'
down_revision = '2c87d4e793c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criteria', sa.Column('adverse', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('criteria', 'adverse')
    # ### end Alembic commands ###
