"""empty message

Revision ID: 956f071f5900
Revises: e1816ccfe087
Create Date: 2021-01-13 21:38:37.603707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956f071f5900'
down_revision = 'e1816ccfe087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('state_category_type_active', 'category_links', ['state', 'category_id', 'type', 'active'], unique=False)
    op.drop_index('state_category_type', table_name='category_links')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('state_category_type', 'category_links', ['state', 'category_id', 'type'], unique=False)
    op.drop_index('state_category_type_active', table_name='category_links')
    # ### end Alembic commands ###
