"""empty message

Revision ID: b880dec4f2c6
Revises: e847dab175d6
Create Date: 2020-12-24 23:29:40.045283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b880dec4f2c6'
down_revision = 'e847dab175d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'subcategories',
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('deactivated_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('help_text', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_subcategories_category_id'),
        'subcategories',
        ['category_id'],
        unique=False,
    )
    op.add_column('criteria', sa.Column('subcategory_id', sa.Integer(), nullable=False))
    op.create_index(
        op.f('ix_criteria_subcategory_id'),
        'criteria',
        ['subcategory_id'],
        unique=False,
    )
    op.drop_index('ix_criteria_category_id', table_name='criteria')
    op.drop_constraint('criteria_category_id_fkey', 'criteria', type_='foreignkey')
    op.create_foreign_key(
        'criteria_subcategory_id_fkey',
        'criteria',
        'subcategories',
        ['subcategory_id'],
        ['id'],
    )
    op.drop_column('criteria', 'category_id')
    op.add_column('links', sa.Column('subcategory_id', sa.Integer(), nullable=False))
    op.create_index('state_subcategory', 'links', ['state', 'subcategory_id'], unique=False)
    op.drop_index('state_category', table_name='links')
    op.drop_constraint('links_category_id_fkey', 'links', type_='foreignkey')
    op.create_foreign_key(
        'links_subcategory_id_fkey',
        'links',
        'subcategories',
        ['subcategory_id'],
        ['id'],
    )
    op.drop_column('links', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'links',
        sa.Column(
            'category_id',
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint('links_subcategory_id_fkey', 'links', type_='foreignkey')
    op.create_foreign_key('links_category_id_fkey', 'links', 'categories', ['category_id'], ['id'])
    op.create_index('state_category', 'links', ['state', 'category_id'], unique=False)
    op.drop_index('state_subcategory', table_name='links')
    op.drop_column('links', 'subcategory_id')
    op.add_column(
        'criteria',
        sa.Column(
            'category_id',
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint('criteria_subcategory_id_fkey', 'criteria', type_='foreignkey')
    op.create_foreign_key(
        'criteria_category_id_fkey',
        'criteria',
        'categories',
        ['category_id'],
        ['id'],
    )
    op.create_index(
        'ix_criteria_category_id',
        'criteria',
        ['category_id'],
        unique=False,
    )
    op.drop_index(op.f('ix_criteria_subcategory_id'), table_name='criteria')
    op.drop_column('criteria', 'subcategory_id')
    op.drop_index(op.f('ix_subcategories_category_id'), table_name='subcategories')
    op.drop_table('subcategories')
    # ### end Alembic commands ###
