"""empty message

Revision ID: c2dc0993746b
Revises: 86927994d09e
Create Date: 2021-01-12 23:20:02.335995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2dc0993746b'
down_revision = '86927994d09e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_links', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index('state_category', 'category_links', ['state', 'category_id'], unique=False)
    op.drop_index('state_category_type', table_name='category_links')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('state_category_type', 'category_links', ['state', 'category_id', 'type'], unique=True)
    op.drop_index('state_category', table_name='category_links')
    op.drop_column('category_links', 'created_at')
    # ### end Alembic commands ###
