"""empty message

Revision ID: c2f28eca200f
Revises: 16600183a58f
Create Date: 2020-11-01 21:30:16.529108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f28eca200f'
down_revision = '16600183a58f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('state_criterion', table_name='links')
    op.drop_table('links')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('criterion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['criterion_id'], ['criteria.id'], name='links_criterion_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='links_pkey')
    )
    op.create_index('state_criterion', 'links', ['state', 'criterion_id'], unique=False)
    # ### end Alembic commands ###
