"""empty message

Revision ID: d05d8a998a58
Revises: 5460b36b985f
Create Date: 2020-11-16 12:44:05.907414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05d8a998a58'
down_revision = '5460b36b985f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    op.add_column('criteria', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('criteria', 'deactivated_at')
    op.drop_column('categories', 'deactivated_at')
    # ### end Alembic commands ###
