"""empty message

Revision ID: d7c80ade926a
Revises: c2f28eca200f
Create Date: 2020-11-01 21:30:35.591862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c80ade926a'
down_revision = 'c2f28eca200f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['criterion_id'], ['criteria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('state_criterion', 'links', ['state', 'criterion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('state_criterion', table_name='links')
    op.drop_table('links')
    # ### end Alembic commands ###
