"""empty message

Revision ID: e1816ccfe087
Revises: c2dc0993746b
Create Date: 2021-01-12 23:35:58.463971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1816ccfe087'
down_revision = 'c2dc0993746b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('state_category_type', 'category_links', ['state', 'category_id', 'type'], unique=False)
    op.drop_index('state_category', table_name='category_links')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('state_category', 'category_links', ['state', 'category_id'], unique=False)
    op.drop_index('state_category_type', table_name='category_links')
    # ### end Alembic commands ###
