"""empty message

Revision ID: ea276fcdfa35
Revises: b880dec4f2c6
Create Date: 2020-12-26 11:13:01.025256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea276fcdfa35'
down_revision = 'b880dec4f2c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'state_category_grades',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('state_code', sa.String(length=2), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('grade', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.ForeignKeyConstraint(['state_code'], ['states.code'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'state_grades',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('state_code', sa.String(length=2), nullable=False),
        sa.Column('grade', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['state_code'], ['states.code'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('state_grades')
    op.drop_table('state_category_grades')
    # ### end Alembic commands ###
