"""empty message

Revision ID: ff69a5c5f4a3
Revises: 4b4cc49e9ce1
Create Date: 2021-01-24 20:29:39.079993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff69a5c5f4a3'
down_revision = '4b4cc49e9ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'description')
    # ### end Alembic commands ###
